spring:
  graphql:
    graphiql:
      enabled: true
    path: /graphql

server:
  port: 8080
  address: localhost

async: false

sender:
  kafka:
    topic: sender_receiver
    brokers: localhost:9092
    enabled: false
  rabbit:
    enabled: false
    exchange:
      direct: false
      fanout: false
    general-properties:
      host-name: localhost
      username: user
      password: password
      virtual-host: sender_receiver_host
      queues:
        sender_receiver_queue_1: sr_key_1
        sender_receiver_queue_2: sr_key_2
    exchanges:
      - sender_receiver_direct
      - sender_receiver_fanout

cxf:
  path: /services
